on: [push]
name: build
jobs:
  runhaskell:
    name: MOS6502 Tests
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.1' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.6.2.0' # Exact version of Cabal
      - run: cabal build shrimp-test
      - run: cabal run shrimp-test
